# 기본이미지 선택
FROM ubuntu:18.04
# 리눅스 설치 : 유틸리티 프로그램 설치 : apt-get
# iputils-ping net-tools git vim
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install iputils-ping -y
RUN apt-get install -y net-tools
RUN apt-get install -y git
RUN apt-get install -y sudo
RUN apt-get install -y vim
